name: ColorfulTag
main: Pocketwarriors\colors\main
version: 0.5
api: [1.12.0]
load: POSTWORLD
authors: [Wantedkillers (Author)]
website: github.com/PocketWarriors/ColorfulTag

commands:
    tag:
    description: make your name blue
    usage: /tagblue
permissions: tag.command
    default: op
 children:
   tag.command.blue:
    description: ""
    default: op
   tag.command:
    description: "Runs all commands"
    default: op
    children:
     tag.command.red:
      description: ""
      default: true
     tag.command.green:
      description: ""
      default: true
    tag.command.gold:
      description: ""
      default: true
