name: ColorfulTag
main: Pocketwarriors\colors\Main
version: 0.5
api: [1.12.0]
load: POSTWORLD
authors: [Wantedkillers (Author)]
website: github.com/PocketWarriors/ColorfulTag

commands:
    tag:
    description: "make your name blue"
    usage: "/tag"
permissions:
tag.command:
 description: "make your name blue"
 default: op
